# Generated by Django 5.0.7 on 2024-07-21 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('hispanic', models.BooleanField()),
                ('ethnicity', models.CharField(choices=[('AI', 'American Indian or Alask Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('PI', 'Native Hawaiian or Pacific Islander'), ('W', 'White'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('W', 'Women'), ('TM', 'Trans Male'), ('TW', 'Trans Women'), ('NC', 'NonConforming'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=50)),
                ('orientation', models.CharField(choices=[('H', 'Heterosexual'), ('G', 'Homosexual'), ('B', 'Bisexual'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=50)),
                ('UScitizenship', models.BooleanField()),
                ('noncitizen', models.CharField(choices=[('1', 'Permanent Resident (Green Card)'), ('2', 'F-1 Visa'), ('3', 'J-1 Visa'), ('4', 'H-1B Visa'), ('4', 'DACA'), ('5', 'Asylum Seeker'), ('0', 'Other Noncitizen Designation')], default='N/A', max_length=1)),
                ('GrossIncome', models.IntegerField(choices=[('1', '0.00 - 10,000.00'), ('2', '10,000.00 - 25,000.00'), ('3', '25,000.00 - 50,000.00'), ('4', '50,000.00 - 100,000.00'), ('5', 'Over 100,000.00')], default='N/A')),
                ('createdon', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programname', models.CharField(max_length=50)),
                ('degreename', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.degree')),
            ],
        ),
    ]
