# Generated by Django 5.0.7 on 2024-07-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orgtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='degreename',
            new_name='degree_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='createdon',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='UScitizenship',
            new_name='us_citizenship',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='programname',
            new_name='program_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='GrossIncome',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='noncitizen',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degreename',
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_income',
            field=models.CharField(choices=[('1', '0.00 - 10,000.00'), ('2', '10,000.00 - 25,000.00'), ('3', '25,000.00 - 50,000.00'), ('4', '50,000.00 - 100,000.00'), ('5', 'Over 100,000.00')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='non_citizen',
            field=models.CharField(choices=[('1', 'Permanent Resident (Green Card)'), ('2', 'F-1 Visa'), ('3', 'J-1 Visa'), ('4', 'H-1B Visa'), ('4', 'DACA'), ('5', 'Asylum Seeker'), ('0', 'Other Noncitizen Designation')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default='Unknown Institution', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='testapp.degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(choices=[('AI', 'American Indian or Alask Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('PI', 'Native Hawaiian or Pacific Islander'), ('W', 'White'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Women'), ('TM', 'Trans Male'), ('TW', 'Trans Women'), ('NC', 'NonConforming'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='orientation',
            field=models.CharField(choices=[('H', 'Heterosexual'), ('G', 'Homosexual'), ('B', 'Bisexual'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('G', 'Graduated'), ('W', 'Withdrawn'), ('C', 'Current')], max_length=1)),
                ('current_year', models.CharField(choices=[('f', 'freshman'), ('s', 'sophomore'), ('j', 'junior'), ('sn', 'senior')], max_length=2)),
                ('gpa', models.FloatField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='JobInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('internship', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.jposition')),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.orgtype')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.sposition')),
            ],
        ),
    ]
