# Generated by Django 5.0.7 on 2024-08-04 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_jposition_orgtype_sposition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
'''
    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
'''