# Generated by Django 5.0.7 on 2024-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('AI', 'American Indian or Alask Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('PI', 'Native Hawaiian or Pacific Islander'), ('W', 'White'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Women'), ('TM', 'Trans Male'), ('TW', 'Trans Women'), ('NC', 'NonConforming'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gross_income',
            field=models.CharField(blank=True, choices=[('1', '0.00 - 10,000.00'), ('2', '10,000.00 - 25,000.00'), ('3', '25,000.00 - 50,000.00'), ('4', '50,000.00 - 100,000.00'), ('5', 'Over 100,000.00')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hispanic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='non_citizen',
            field=models.CharField(blank=True, choices=[('1', 'Permanent Resident (Green Card)'), ('2', 'F-1 Visa'), ('3', 'J-1 Visa'), ('4', 'H-1B Visa'), ('4', 'DACA'), ('5', 'Asylum Seeker'), ('0', 'Other Noncitizen Designation')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='orientation',
            field=models.CharField(blank=True, choices=[('H', 'Heterosexual'), ('G', 'Homosexual'), ('B', 'Bisexual'), ('O', 'Other'), ('NA', 'Prefer Not to Answer')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='us_citizenship',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
